from flask import Flask, render_template, abort
from waitress import serve
import pandas as pd
import json
import os
import numpy as np

# --- FLASK APP INITIALIZATION ---
app = Flask(__name__)

# --- CONFIGURATION ---
# Paths mapped via Docker volumes
CSV_PATH = '/app/data.csv'
STATUS_PATH = '/app/status.json'

def get_local_status():
    """Reads the real-time status JSON generated by the C++ engine."""
    try:
        with open(STATUS_PATH, 'r') as f:
            return json.load(f)
    except:
        # Return default zero values if file is missing or busy
        return {"equity": 0.0, "cash": 0.0, "invested": 0.0}

def calculate_advanced_metrics(df):
    """
    Calculates quantitative metrics (Sharpe Ratio, Max Drawdown) 
    from the trade history DataFrame.
    """
    # We need at least 2 data points to calculate variance/returns
    if df.empty or len(df) < 2:
        return 0.0, 0.0
    
    try:
        # 1. Reconstruct Equity Curve (Approximate)
        # Formula: Cash + (Holdings * Price at that moment)
        df['equity'] = df['cash_available'] + (df['qty'] * df['price'])
        
        # 2. Calculate Percentage Returns
        df['returns'] = df['equity'].pct_change().dropna()
        
        # 3. Sharpe Ratio (Annualized)
        mean_ret = df['returns'].mean()
        std_ret = df['returns'].std()
        
        if std_ret > 0:
            # Assuming crypto markets (365 days * 24h) for high-frequency adjustments
            # For daily data, sqrt(365) is standard. For hourly, sqrt(365*24).
            sharpe = (mean_ret / std_ret) * np.sqrt(365 * 24) 
        else:
            sharpe = 0.0
            
        # 4. Max Drawdown Calculation
        cum_ret = (1 + df['returns']).cumprod()
        peak = cum_ret.cummax()
        drawdown = (cum_ret - peak) / peak
        max_dd = drawdown.min() * 100 # Convert to percentage
        
        return sharpe, max_dd
    except Exception as e:
        print(f"[ERROR] Analytics calculation failed: {e}")
        return 0.0, 0.0

@app.route('/live-quant-strategy-doge')
def index():
    account = get_local_status()
    
    # --- BASIC PERFORMANCE METRICS ---
    current_equity = account.get('equity', 0)
    last_equity = account.get('last_equity', 100000) # Default to 100k if initial
    initial_capital = 100000.0

    # Daily Return
    if last_equity > 0:
        daily_pct = ((current_equity - last_equity) / last_equity) * 100
    else:
        daily_pct = 0.0

    # Total Return
    total_pct = ((current_equity - initial_capital) / initial_capital) * 100

    account['daily_pct'] = daily_pct
    account['total_pct'] = total_pct

    # --- ADVANCED ANALYTICS (Reading CSV) ---
    try:
        df = pd.read_csv(CSV_PATH)
        df = df.sort_values('timestamp')
        
        sharpe, max_dd = calculate_advanced_metrics(df)
        
        # Get last 50 trades for the table, reversed (newest first)
        trades = df.tail(50).iloc[::-1].to_dict('records')
    except:
        trades = []
        sharpe, max_dd = 0.0, 0.0

    # Inject metrics into the account object for the template
    account['sharpe'] = sharpe
    account['max_dd'] = max_dd

    return render_template('index.html', account=account, trades=trades)

@app.route('/')
def home():
    # Security by obscurity: Access Denied for root scans
    return "Access Denied", 403

if __name__ == '__main__':
    print("Starting Dashboard Server on port 5000...")
    serve(app, host='0.0.0.0', port=5000)
